### ISSUE TITLE
C++ version of rqt_topic

### ISSUE THREAD

**Issue by tonaaskarwur** [ros-visualization/rqt_topic#25]
I am trying to develop my own GUI for ROS. It is somewhat like rqt but with more specific plugins for my robot.
I build it using qt creator, and since I'm pretty new in ROS I tried to combine some sources to the GUI with my limited knowledge.
I use C++ to make the GUI, and I want to add a plugin to visualize the rostopic data (at least for diagnostic), and this is the plugin that I have been searching for.
It seems the code here is written in python, and I am having difficulties on combining them because of my lack understanding of python.
Either I need to translate this the rqt_topic from python to c++, or create a callback function in my GUI to publish "rostopic echo /diagnostics".
Do you have any ideas, suggestion, or reference?
Thank you.

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
